server:
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: prod

  config:
    use-legacy-processing: true

springdoc:
  swagger-ui:
    operationsSorter: method



